# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'ChatDemo-UI3.0' do
    
    pod 'Hyphenate'

    pod 'MWPhotoBrowser', '~> 2.1.2'

#    pod 'GoogleCloudMessaging', '~> 1.2'
    pod 'Google/Analytics'

    pod 'Fabric'
    pod 'Crashlytics'

    pod 'Parse'

end
