# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'ChatDemo-UI3.0' do
    
    # Hyphenate chat
    pod 'Hyphenate', '~> 3.2.3'

    # coffee bot with api.ai
    pod 'ApiAI'
    
    # others
    pod 'MWPhotoBrowser', '~> 2.1.2'

    # Analytics
    pod 'Google/Analytics'
    pod 'Fabric'
    pod 'Crashlytics'

    # database
    pod 'Parse'

end
